version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 80-81:80
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"

    # During the execution of the Ansible playbooks
    # the '.env' file will be uploaded to the EC2 instance
    # and loaded via 'docker-compose --env-file [path] up'

    # Un-comment when running locally.
    # env_file:
    #   - ../.env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    # During the execution of the Ansible playbooks
    # the '.env' file will be uploaded to the EC2 instance
    # and loaded via 'docker-compose --env-file [path] up'

    # Un-comment when running locally.
    # env_file:
    #   - ../.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

