# Ansible playbook: Execute sub-playbooks
---
- name: Set up EC2 instance
  ansible.builtin.import_playbook: ./playbooks/set_up_ec2.yaml

- name: Install Docker & start services
  ansible.builtin.import_playbook: ./playbooks/install_docker.yaml

- name: Seed database
  ansible.builtin.import_playbook: ./playbooks/seed_db.yaml
