---
- name: "Start docker container"
  hosts: webserver
  become: true
  tasks:
    - name: Start WordPress
      become: true
      ansible.builtin.shell: docker run --name wp-server --env WORDPRESS_DB_HOST="ip-10-0-0-201.eu-west-1.compute.internal:3306" --env WORDPRESS_DB_USER=root --env WORDPRESS_DB_PASSWORD=my-secret-pw --env WORDPRESS_DB_NAME=db -p 80:80 -d wordpress

    # - name: Copy docker-compose file with owner and permissions
    #   become: true
    #   ansible.builtin.copy:
    #     src: ../docker/docker-compose-mysql.yaml # use env var
    #     dest: /home/ec2-user/docker-compose.yaml
    #     owner: ec2-user # use env var
    #     group: ec2-user # use env var
    #     mode: "0644"
